export const API_KEY = process.env['API_KEY']
export const AUTH_DOMAIN = process.env['AUTH_DOMAIN']
export const PROJECT_ID = process.env['PROJECT_ID']
export const STORAGE_BUCKET = process.env['STORAGE_BUCKET']
export const MESSAGE_SENDER_ID = process.env['MESSAGE_SENDER_ID']
export const APP_ID = process.env['APP_ID']